version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: eslint
    versions:
    - 7.16.0
  - dependency-name: next
    versions:
    - 10.0.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
